ttt246/Brain

- app.py
- requirements.txt
- src/common/assembler.py
- src/model/contact_model.py
- src/model/requests/request_model.py
- src/model/sms_model.py
- src/router/api.py
- tests/conftest.py
- tests/functional/test_recipes.py
> feature(#13)

- README.md
- src/common/assembler.py
- tests/conftest.py
close #13 updated readme and removed package from sourcecode, which is not using with flask
> feature(#13): 

- src/rising_plugin/risingplugin.py
close(#12):
Fix json parsing issue in risingplugin.py file.
> feature(#12)

- src/common/utils.py
- src/rising_plugin/risingplugin.py
fxied #32 json parsing issue fixed.
> feature(#32)

- src/common/assembler.py
- src/common/program_type.py
- src/rising_plugin/risingplugin.py
- src/router/browser_router.py
- src/service/browser_service.py
fixed #32 
fixed selection_item function to get  only its link from the list with the format. And adjustify its temperature.
> feature(#32): 

- .gitignore
- Brain/src/common/brain_exception.py
- Brain/src/rising_plugin/guardrails-config/actions/actions.py
- Brain/src/rising_plugin/guardrails-config/general.co
- Brain/src/rising_plugin/risingplugin.py
close #45 
Actions-Rails: Issues Fixed to pass its argument
> feature(#45)

- app.py
close #82 CORS Error for extension
> bugfix(#82)

- Brain/src/common/assembler.py
- Brain/src/firebase/firebase.py
- Brain/src/model/requests/request_model.py
- Brain/src/router/api.py
- Brain/src/router/browser_router.py
updated #9 updated request body type with confs.
> feature(#9)

- Brain/tests/functional/test_api.py
close #85 Implement FastApi Unit Test For Api Endpoints
> feature(#85)

- Brain/tests/functional/test_api.py
close #85 Implement FastApi Unit Test For Api Endpoints
> feature(#85): Implement FastApi Unit Test For Api Endpoints

- Extension/src/pages/Panel/Panel.jsx
> [bugfix #111] no activity with the prompt in extension

- Android/app/src/main/java/com/matthaigh27/chatgptwrapper/data/remote/ApiService.kt
- Android/app/src/main/java/com/matthaigh27/chatgptwrapper/data/remote/responses/ImageRelatenessApiResponse.kt
- Android/app/src/main/java/com/matthaigh27/chatgptwrapper/data/repository/RemoteRepository.kt
- Android/app/src/main/java/com/matthaigh27/chatgptwrapper/ui/chat/view/adapters/ChatMainAdapter.kt
- Android/app/src/main/java/com/matthaigh27/chatgptwrapper/ui/chat/view/fragments/ChatMainFragment.kt
- Android/app/src/main/java/com/matthaigh27/chatgptwrapper/ui/chat/viewmodel/ChatViewModel.kt
- Android/app/src/main/java/com/matthaigh27/chatgptwrapper/ui/setting/view/SettingActivity.kt
- Android/app/src/main/res/layout/activity_setting.xml
- Android/app/src/main/res/values/colors.xml
- Android/app/src/main/res/values/strings.xml
- Android/app/src/main/res/values/styles.xml
> feature(#105): update setting menu and fix that app isn't installed.

- LICENSE
> feature(#104): added MIT License

- Brain/src/gradio_debug.py
- app.py
- requirements.txt
close #86 implement debug ui for sendNotification function with gradio
> feature(#86): implement debug ui for sendNotification function

- Brain/src/model/requests/request_model.py
- Brain/src/router/api.py
- Brain/src/service/auto_task_service.py
- Brain/tests/functional/test_api.py
> Instant Answer in extension

- Brain/src/rising_plugin/llm/llms.py
- Extension/src/pages/Panel/Panel.jsx
bugfix(update_api): update api of extensions according to llm model changes
> Bugfix: Update api in extensions

- Brain/src/commands/command.py
> feature(#130): update command API response format

- README.md
> feature(#144): updated readme from root directory - Brain.

- README.md
> feature(#144): updated readme title style

- .sauce/config.yml
bugfix #182 
saucelabs test for upload image and image relatedness functions.
> bugfix(#182): saucelabs test

- Brain/src/rising_plugin/guardrails-config/general.co
close #199 
Urgent Issue for Gaudrails
> bugfix(#199):  Urgent Issue for Gaudrails

- sauce_tests/01 Send Notification/README.md
- sauce_tests/02 Upload Image/README.md
- sauce_tests/03 Image Relatedness/README.md
bugfix: 
updated saucelabs api test syntax link.
> bugfix: updated saucelabs api test syntax link.

- Android/README.md
Remove some URL on Android readme
> feature(#144): Update Android Readme

- Brain/src/rising_plugin/gmail/email_plugin.py
- Brain/src/router/email_router.py
> Email Feature: File Attachment

- Brain/src/rising_plugin/guardrails-config/general.co
close
manage on-topic wit more greetings.
> bugfix: implement on-topic with more greetings for brain.

- Brain/src/rising_plugin/gmail/email_plugin.py
> bugfix: smtp port for email access.

- Android/app/src/main/java/com/matthaigh27/chatgptwrapper/ui/chat/view/adapters/ChatMainAdapter.kt
- Android/app/src/main/java/com/matthaigh27/chatgptwrapper/ui/chat/view/widgets/chatwidget/mail/ComposeMailWidget.kt
- Android/app/src/main/res/layout/widget_mail_compose.xml
> feature(#99): complete interface that users can read or send mails

- Brain/src/common/utils.py
- Brain/src/rising_plugin/gmail/email_plugin.py
- Brain/src/router/email_router.py
- requirements.txt
close:
proxy setup for imap access in hugging face.
> feature: proxy setup for imap access in hugging face.

- Brain/README.md
I don't think we need the readme
> Simplify readme

- Brain/src/model/req_model.py
> feature: implemented the base64 decode module for firebase key.

- Extension/src/pages/Background/index.js
- Extension/src/pages/Panel/Panel.css
- Extension/src/pages/Panel/Panel.jsx
- Extension/src/pages/Popup/Popup.css
- Extension/src/pages/Popup/Popup.jsx
- Extension/src/pages/Popup/index.css
> Setting page in Extension
